version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-cdap
    privileged: true                  # нужно для Docker-in-Docker
    user: root
    ports:
      - "8080:8080"                   # веб-интерфейс
      - "50000:50000"                 # агентам
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   # доступ к Docker хоста
      - ~/.kube:/root/.kube:ro                      # твой Minikube kubeconfig
    restart: unless-stopped

volumes:
  jenkins_home: